"""Pool fixo de 20 tasks v3 estratificadas para o Teste de sinergia contexto×constantes.

Três estratos:

- Estrato S (sinergia, prefixo s_): prompts >600 chars cujos primeiros 240 chars
  contêm APENAS apresentação genérica (arquivos, nomes de função, propósito).
  Todas as constantes críticas aparecem APÓS o char 240 — se o summarize truncar
  o enunciado, elas se perdem. Cada task tem exatamente 2 arquivos: um helper
  trivial SEM constantes críticas e solution.py que usa todas. Todo valor
  esperado nos asserts é COMPOSTO de >=2 constantes críticas, de modo que o
  output do pytest (que vaza valores esperados) não permite recuperar nenhuma
  constante individual.

- Estrato C (controle, prefixo c_): prompts >600 chars cujas constantes críticas
  aparecem TODAS dentro dos primeiros 240 chars; o restante do enunciado é
  apenas elaboração redundante. 1 arquivo (solution.py). Truncar aos 240 chars
  não remove informação necessária.

- Estrato L (longo, prefixo l_): prompts >800 chars com trajetórias longas e
  reward pouco saturável: exatamente 3 arquivos (2 helpers + solution.py),
  cada helper com >=1 constante crítica própria, e >=10 funções de teste
  (helpers testados separadamente + integração). Como no estrato S, os
  primeiros 240 chars são só apresentação genérica e TODAS as constantes
  críticas (decimais arbitrários, códigos ERR_NN) aparecem APÓS o char 240.
  5 tasks moderadas e 5 difíceis (regras encadeadas em ordem obrigatória,
  parsers com múltiplos códigos de erro, máquinas de estado).

Ambos os estratos usam imports DENTRO das funções de teste para reward gradual
(arquivos ausentes causam falhas individuais, não erro de coleta).
"""

TASKS: list[dict] = [
    # ------------------------- ESTRATO S -------------------------
    {
        "task_id": "s_freight_quote",
        "prompt": (
            "You are asked to implement a freight quoting module for a logistics\n"
            "company. The work is split across two files that you must create in the\n"
            "workspace: a small numeric helper file and the main entry point file\n"
            "solution.py that the tests call. Read every rule below carefully: the\n"
            "exact business constants matter and cannot be derived from the code.\n\n"
            "Files and functions:\n"
            "1. shipping_utils.py must define `round2(x: float) -> float` returning\n"
            "   `round(x, 2)`.\n"
            "2. solution.py must define\n"
            "   `freight_quote(weight_kg: float, express: bool) -> float` computed\n"
            "   in this exact order:\n"
            "   - Start with a flat base fee of 14.75 plus 3.85 per kilogram\n"
            "     (weight_kg * 3.85).\n"
            "   - Heavy surcharge: if weight_kg is STRICTLY greater than 22.5,\n"
            "     multiply the quote by 1.12 (at exactly 22.5 there is no surcharge).\n"
            "   - Express: if express is True, multiply the quote by 1.45 at the end.\n"
            "   Return the final quote passed through round2.\n"
        ),
        "starter_code": (
            "def freight_quote(weight_kg: float, express: bool) -> float:\n"
            '    """Compute the freight quote for a shipment."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_round2():\n"
            "    from shipping_utils import round2\n"
            "    assert round2(3.14159) == 3.14\n"
            "\n"
            "\n"
            "def test_standard_ten_kg():\n"
            "    from solution import freight_quote\n"
            "    assert freight_quote(10.0, False) == 53.25\n"
            "\n"
            "\n"
            "def test_standard_one_kg():\n"
            "    from solution import freight_quote\n"
            "    assert freight_quote(1.0, False) == 18.6\n"
            "\n"
            "\n"
            "def test_zero_weight_express():\n"
            "    from solution import freight_quote\n"
            "    assert freight_quote(0.0, True) == 21.39\n"
            "\n"
            "\n"
            "def test_heavy_shipment():\n"
            "    from solution import freight_quote\n"
            "    assert freight_quote(30.0, False) == 145.88\n"
            "\n"
            "\n"
            "def test_just_above_heavy_threshold():\n"
            "    from solution import freight_quote\n"
            "    assert freight_quote(23, False) == 115.7\n"
            "\n"
            "\n"
            "def test_just_below_heavy_threshold():\n"
            "    from solution import freight_quote\n"
            "    assert freight_quote(22, False) == 99.45\n"
            "\n"
            "\n"
            "def test_heavy_and_express():\n"
            "    from solution import freight_quote\n"
            "    assert freight_quote(23, True) == 167.76\n"
            "\n"
            "\n"
            "def test_light_express():\n"
            "    from solution import freight_quote\n"
            "    assert freight_quote(5.0, True) == 49.3\n"
        ),
    },
    {
        "task_id": "s_ticket_pricer",
        "prompt": (
            "You are asked to implement a museum ticket pricing module. The work is\n"
            "split across two files that you must create in the workspace: a small\n"
            "calendar helper file and the main entry point file solution.py that the\n"
            "tests call. The pricing constants below are arbitrary business rules\n"
            "and must be followed exactly as written, in the given order.\n\n"
            "Files and functions:\n"
            "1. calendar_utils.py must define `is_weekend(day: str) -> bool` returning\n"
            "   True iff day is 'sat' or 'sun' (lowercase three-letter codes).\n"
            "2. solution.py must define `ticket_price(age: int, day: str) -> float`\n"
            "   computed in this exact order:\n"
            "   - Start from the adult base price of 48.20.\n"
            "   - If age < 12, multiply the base by 0.35; otherwise if age >= 65,\n"
            "     multiply the base by 0.55 (only one multiplier ever applies).\n"
            "   - Add a fixed booking fee of 4.15.\n"
            "   - If is_weekend(day), add a weekend surcharge of 6.60.\n"
            "   Return the result rounded to 2 decimal places with round(x, 2).\n"
        ),
        "starter_code": (
            "def ticket_price(age: int, day: str) -> float:\n"
            '    """Compute the ticket price for a visitor age on a given day."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_weekend_true():\n"
            "    from calendar_utils import is_weekend\n"
            "    assert is_weekend('sat') is True and is_weekend('sun') is True\n"
            "\n"
            "\n"
            "def test_helper_weekday_false():\n"
            "    from calendar_utils import is_weekend\n"
            "    assert is_weekend('mon') is False\n"
            "\n"
            "\n"
            "def test_adult_weekday():\n"
            "    from solution import ticket_price\n"
            "    assert ticket_price(30, 'mon') == 52.35\n"
            "\n"
            "\n"
            "def test_child_weekday():\n"
            "    from solution import ticket_price\n"
            "    assert ticket_price(8, 'tue') == 21.02\n"
            "\n"
            "\n"
            "def test_senior_weekday():\n"
            "    from solution import ticket_price\n"
            "    assert ticket_price(70, 'wed') == 30.66\n"
            "\n"
            "\n"
            "def test_adult_weekend():\n"
            "    from solution import ticket_price\n"
            "    assert ticket_price(30, 'sat') == 58.95\n"
            "\n"
            "\n"
            "def test_child_weekend():\n"
            "    from solution import ticket_price\n"
            "    assert ticket_price(8, 'sun') == 27.62\n"
            "\n"
            "\n"
            "def test_senior_weekend():\n"
            "    from solution import ticket_price\n"
            "    assert ticket_price(70, 'sat') == 37.26\n"
            "\n"
            "\n"
            "def test_child_boundary_ages():\n"
            "    from solution import ticket_price\n"
            "    assert ticket_price(11, 'mon') == 21.02\n"
            "    assert ticket_price(12, 'mon') == 52.35\n"
            "\n"
            "\n"
            "def test_senior_boundary_ages():\n"
            "    from solution import ticket_price\n"
            "    assert ticket_price(64, 'fri') == 52.35\n"
            "    assert ticket_price(66, 'thu') == 30.66\n"
        ),
    },
    {
        "task_id": "s_sensor_alarm",
        "prompt": (
            "You are asked to implement an industrial sensor alarm scorer. The work\n"
            "is split across two files that you must create in the workspace: a tiny\n"
            "statistics helper file and the main entry point file solution.py that\n"
            "the tests call. The alarm thresholds and scaling factors given below\n"
            "are calibration constants; follow them exactly as written.\n\n"
            "Files and functions:\n"
            "1. readings_utils.py must define `mean(values: list[float]) -> float`\n"
            "   returning `sum(values) / len(values)` (input is never empty).\n"
            "2. solution.py must define `alarm_level(values: list[float]) -> float`.\n"
            "   Let m = mean(values). Then, checked from the top:\n"
            "   - if m is STRICTLY greater than 71.4, return round(m * 1.65 + 4.35, 2);\n"
            "   - otherwise, if m is STRICTLY greater than 33.8, return\n"
            "     round((m + 15.9) * 1.15, 2);\n"
            "   - otherwise return round(m * 0.25 + 8.2, 2).\n"
            "   Exactly one branch applies; the two thresholds are strict.\n"
        ),
        "starter_code": (
            "def alarm_level(values: list[float]) -> float:\n"
            '    """Score the alarm level for a window of sensor readings."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_mean():\n"
            "    from readings_utils import mean\n"
            "    assert mean([2, 4]) == 3.0\n"
            "\n"
            "\n"
            "def test_high_band():\n"
            "    from solution import alarm_level\n"
            "    assert alarm_level([80, 80]) == 136.35\n"
            "\n"
            "\n"
            "def test_mid_band():\n"
            "    from solution import alarm_level\n"
            "    assert alarm_level([40]) == 64.28\n"
            "\n"
            "\n"
            "def test_low_band():\n"
            "    from solution import alarm_level\n"
            "    assert alarm_level([10, 20]) == 11.95\n"
            "\n"
            "\n"
            "def test_just_below_high_threshold():\n"
            "    from solution import alarm_level\n"
            "    assert alarm_level([71]) == 99.94\n"
            "\n"
            "\n"
            "def test_just_above_high_threshold():\n"
            "    from solution import alarm_level\n"
            "    assert alarm_level([72]) == 123.15\n"
            "\n"
            "\n"
            "def test_just_below_mid_threshold():\n"
            "    from solution import alarm_level\n"
            "    assert alarm_level([33]) == 16.45\n"
            "\n"
            "\n"
            "def test_just_above_mid_threshold():\n"
            "    from solution import alarm_level\n"
            "    assert alarm_level([34]) == 57.38\n"
            "\n"
            "\n"
            "def test_high_band_single_reading():\n"
            "    from solution import alarm_level\n"
            "    assert alarm_level([100]) == 169.35\n"
            "\n"
            "\n"
            "def test_mid_band_two_readings():\n"
            "    from solution import alarm_level\n"
            "    assert alarm_level([50, 60]) == 81.53\n"
        ),
    },
    {
        "task_id": "s_commission_calc",
        "prompt": (
            "You are asked to implement a sales commission calculator. The work is\n"
            "split across two files that you must create in the workspace: a small\n"
            "aggregation helper file and the main entry point file solution.py that\n"
            "the tests call. The commission rates, tier thresholds and bonuses given\n"
            "below are contractual constants and must be applied exactly as stated.\n\n"
            "Files and functions:\n"
            "1. sales_utils.py must define `total(sales: list[float]) -> float`\n"
            "   returning `float(sum(sales))`.\n"
            "2. solution.py must define `commission(sales: list[float]) -> float`.\n"
            "   Let t = total(sales). Then, in this exact order:\n"
            "   - Rate: use 0.083 if t is STRICTLY greater than 5400, otherwise use\n"
            "     0.047 (at exactly 5400 the lower rate applies).\n"
            "   - Commission: t times the rate, plus a fixed stipend of 62.5.\n"
            "   - Top-seller bonus: if t is STRICTLY greater than 9100, add a flat\n"
            "     175.0 on top (at exactly 9100 there is no bonus).\n"
            "   Return the result rounded to 2 decimal places with round(x, 2).\n"
        ),
        "starter_code": (
            "def commission(sales: list[float]) -> float:\n"
            '    """Compute the commission owed for a list of sale amounts."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_total():\n"
            "    from sales_utils import total\n"
            "    assert total([1, 2, 3]) == 6\n"
            "\n"
            "\n"
            "def test_low_tier_small():\n"
            "    from solution import commission\n"
            "    assert commission([1000]) == 109.5\n"
            "\n"
            "\n"
            "def test_low_tier_medium():\n"
            "    from solution import commission\n"
            "    assert commission([5000]) == 297.5\n"
            "\n"
            "\n"
            "def test_high_tier():\n"
            "    from solution import commission\n"
            "    assert commission([6000]) == 560.5\n"
            "\n"
            "\n"
            "def test_just_below_rate_threshold():\n"
            "    from solution import commission\n"
            "    assert commission([5399]) == 316.25\n"
            "\n"
            "\n"
            "def test_just_above_rate_threshold():\n"
            "    from solution import commission\n"
            "    assert commission([5401]) == 510.78\n"
            "\n"
            "\n"
            "def test_just_below_bonus_threshold():\n"
            "    from solution import commission\n"
            "    assert commission([9099]) == 817.72\n"
            "\n"
            "\n"
            "def test_just_above_bonus_threshold():\n"
            "    from solution import commission\n"
            "    assert commission([9101]) == 992.88\n"
            "\n"
            "\n"
            "def test_big_seller_with_bonus():\n"
            "    from solution import commission\n"
            "    assert commission([10000]) == 1067.5\n"
            "\n"
            "\n"
            "def test_multiple_sales_summed():\n"
            "    from solution import commission\n"
            "    assert commission([2000, 500]) == 180.0\n"
        ),
    },
    {
        "task_id": "s_energy_bill",
        "prompt": (
            "You are asked to implement an electricity billing module. The work is\n"
            "split across two files that you must create in the workspace: a meter\n"
            "reading helper file and the main entry point file solution.py that the\n"
            "tests call. The tariff constants below come from the utility contract\n"
            "and must be applied exactly, in the stated order.\n\n"
            "Files and functions:\n"
            "1. meter_utils.py must define `usage(start: float, end: float) -> float`\n"
            "   returning `end - start` (the consumed units).\n"
            "2. solution.py must define\n"
            "   `bill(start: float, end: float, night: bool) -> float`.\n"
            "   Let u = usage(start, end). Then, in this exact order:\n"
            "   - Base cost: u * 0.6175 plus a fixed connection charge of 21.45.\n"
            "   - Peak surcharge: if u is STRICTLY greater than 240, add\n"
            "     (u - 240) * 0.29 for the excess units only.\n"
            "   - Night plan: if night is True, multiply the whole amount by 0.93\n"
            "     at the very end.\n"
            "   Return the result rounded to 2 decimal places with round(x, 2).\n"
        ),
        "starter_code": (
            "def bill(start: float, end: float, night: bool) -> float:\n"
            '    """Compute the electricity bill between two meter readings."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_usage():\n"
            "    from meter_utils import usage\n"
            "    assert usage(10, 25) == 15\n"
            "\n"
            "\n"
            "def test_small_usage_day():\n"
            "    from solution import bill\n"
            "    assert bill(50, 150, False) == 83.2\n"
            "\n"
            "\n"
            "def test_small_usage_night():\n"
            "    from solution import bill\n"
            "    assert bill(50, 150, True) == 77.38\n"
            "\n"
            "\n"
            "def test_peak_surcharge_day():\n"
            "    from solution import bill\n"
            "    assert bill(0, 300, False) == 224.1\n"
            "\n"
            "\n"
            "def test_peak_surcharge_other_readings():\n"
            "    from solution import bill\n"
            "    assert bill(40, 300, False) == 187.8\n"
            "\n"
            "\n"
            "def test_medium_usage_day():\n"
            "    from solution import bill\n"
            "    assert bill(0, 200, False) == 144.95\n"
            "\n"
            "\n"
            "def test_medium_usage_night():\n"
            "    from solution import bill\n"
            "    assert bill(0, 200, True) == 134.8\n"
            "\n"
            "\n"
            "def test_just_above_peak_threshold():\n"
            "    from solution import bill\n"
            "    assert bill(100, 341, False) == 170.56\n"
            "\n"
            "\n"
            "def test_peak_and_night_combined():\n"
            "    from solution import bill\n"
            "    assert bill(0, 300, True) == 208.41\n"
        ),
    },
    # ------------------------- ESTRATO C -------------------------
    {
        "task_id": "c_temp_label",
        "prompt": (
            "Create solution.py defining `label(c: float) -> str`: return 'COLD' if\n"
            "c < 8.5, 'MILD' if 8.5 <= c < 27.0, otherwise 'HOT'; then append '!' to\n"
            "the label whenever c > 39.5. The constants 8.5, 27.0 and 39.5 are exact.\n\n"
            "To restate the very same rules step by step: you look at the temperature\n"
            "c and pick one of the three labels using the two cutoffs already given\n"
            "above, then independently decide whether to add the exclamation mark\n"
            "using the third cutoff already given above. For example, a temperature\n"
            "below the first cutoff yields the cold label; a temperature at or above\n"
            "the first cutoff but below the second yields the mild label; anything at\n"
            "or above the second cutoff yields the hot label. Finally, if and only if\n"
            "the temperature strictly exceeds the third cutoff, one exclamation mark\n"
            "is appended to whatever label was chosen. Nothing else is ever appended,\n"
            "and no other threshold exists beyond the three numbers stated in the\n"
            "first paragraph.\n"
        ),
        "starter_code": (
            "def label(c: float) -> str:\n"
            '    """Return the display label for a temperature in Celsius."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_cold():\n"
            "    from solution import label\n"
            "    assert label(0.0) == 'COLD'\n"
            "\n"
            "\n"
            "def test_cold_boundary():\n"
            "    from solution import label\n"
            "    assert label(8.4) == 'COLD'\n"
            "\n"
            "\n"
            "def test_mild_lower_boundary():\n"
            "    from solution import label\n"
            "    assert label(8.5) == 'MILD'\n"
            "\n"
            "\n"
            "def test_mild_upper_boundary():\n"
            "    from solution import label\n"
            "    assert label(26.9) == 'MILD'\n"
            "\n"
            "\n"
            "def test_hot_boundary():\n"
            "    from solution import label\n"
            "    assert label(27.0) == 'HOT'\n"
            "\n"
            "\n"
            "def test_no_bang_at_exact_threshold():\n"
            "    from solution import label\n"
            "    assert label(39.5) == 'HOT'\n"
            "\n"
            "\n"
            "def test_bang_above_threshold():\n"
            "    from solution import label\n"
            "    assert label(39.6) == 'HOT!'\n"
            "\n"
            "\n"
            "def test_negative_is_cold():\n"
            "    from solution import label\n"
            "    assert label(-5.0) == 'COLD'\n"
            "\n"
            "\n"
            "def test_very_hot():\n"
            "    from solution import label\n"
            "    assert label(100.0) == 'HOT!'\n"
        ),
    },
    {
        "task_id": "c_late_fee",
        "prompt": (
            "Create solution.py defining `late_fee(days: int) -> float`: return 0.0\n"
            "if days <= 0; otherwise fee = days * 2.75 + 8.0; if days > 30 add 55.0\n"
            "more; return round(fee, 2). All four constants are exact and mandatory.\n\n"
            "To walk through the very same computation again in words: when nothing\n"
            "is overdue (zero days or a negative input) the caller owes nothing at\n"
            "all, so the function returns the float zero. When at least one day is\n"
            "overdue, the fee grows linearly with the number of days at the per-day\n"
            "rate stated in the first sentence, on top of the flat handling amount\n"
            "also stated in the first sentence. When the delay is longer than the\n"
            "day-count threshold stated in the first sentence, one extra flat penalty\n"
            "(the fourth constant above) is added a single time — it is not\n"
            "multiplied by anything. The final value is always rounded to two\n"
            "decimal places before being returned, exactly as written above.\n"
        ),
        "starter_code": (
            "def late_fee(days: int) -> float:\n"
            '    """Compute the late-return fee for a rental overdue by `days`."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_zero_days():\n"
            "    from solution import late_fee\n"
            "    assert late_fee(0) == 0.0\n"
            "\n"
            "\n"
            "def test_negative_days():\n"
            "    from solution import late_fee\n"
            "    assert late_fee(-3) == 0.0\n"
            "\n"
            "\n"
            "def test_one_day():\n"
            "    from solution import late_fee\n"
            "    assert late_fee(1) == 10.75\n"
            "\n"
            "\n"
            "def test_two_days():\n"
            "    from solution import late_fee\n"
            "    assert late_fee(2) == 13.5\n"
            "\n"
            "\n"
            "def test_ten_days():\n"
            "    from solution import late_fee\n"
            "    assert late_fee(10) == 35.5\n"
            "\n"
            "\n"
            "def test_no_penalty_at_exact_threshold():\n"
            "    from solution import late_fee\n"
            "    assert late_fee(30) == 90.5\n"
            "\n"
            "\n"
            "def test_penalty_above_threshold():\n"
            "    from solution import late_fee\n"
            "    assert late_fee(31) == 148.25\n"
            "\n"
            "\n"
            "def test_long_delay():\n"
            "    from solution import late_fee\n"
            "    assert late_fee(60) == 228.0\n"
        ),
    },
    {
        "task_id": "c_username_check",
        "prompt": (
            "Create solution.py defining `check(u: str) -> str`: return 'ERR_LEN' if\n"
            "len(u) < 5 or len(u) > 14; return 'ERR_CHAR' if u contains anything\n"
            "besides lowercase a-z, digits or '_'; otherwise return 'OK:' + u.\n\n"
            "Restating the exact same policy in plain words: the length rule is\n"
            "checked first, so a username that is both too short and full of illegal\n"
            "characters still gets the length error code from the first sentence.\n"
            "Only when the length is inside the inclusive range implied above does\n"
            "the character rule run: every single character must be a lowercase\n"
            "ASCII letter, a decimal digit, or the underscore; uppercase letters,\n"
            "spaces and punctuation all trigger the character error code from the\n"
            "first sentence. A username that passes both checks is echoed back with\n"
            "the two-character prefix and colon shown above glued directly in front\n"
            "of it, with no added spaces and no other transformation of any kind.\n"
        ),
        "starter_code": (
            "def check(u: str) -> str:\n"
            '    """Validate a username and return a status string."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_valid_minimal_length():\n"
            "    from solution import check\n"
            "    assert check('abcde') == 'OK:abcde'\n"
            "\n"
            "\n"
            "def test_too_short():\n"
            "    from solution import check\n"
            "    assert check('abcd') == 'ERR_LEN'\n"
            "\n"
            "\n"
            "def test_valid_maximal_length():\n"
            "    from solution import check\n"
            "    assert check('aaaaaaaaaaaaaa') == 'OK:aaaaaaaaaaaaaa'\n"
            "\n"
            "\n"
            "def test_too_long():\n"
            "    from solution import check\n"
            "    assert check('aaaaaaaaaaaaaaa') == 'ERR_LEN'\n"
            "\n"
            "\n"
            "def test_underscore_and_digit_ok():\n"
            "    from solution import check\n"
            "    assert check('user_1') == 'OK:user_1'\n"
            "\n"
            "\n"
            "def test_uppercase_rejected():\n"
            "    from solution import check\n"
            "    assert check('User1x') == 'ERR_CHAR'\n"
            "\n"
            "\n"
            "def test_space_rejected():\n"
            "    from solution import check\n"
            "    assert check('abc de') == 'ERR_CHAR'\n"
            "\n"
            "\n"
            "def test_empty_is_len_error():\n"
            "    from solution import check\n"
            "    assert check('') == 'ERR_LEN'\n"
            "\n"
            "\n"
            "def test_typical_valid_name():\n"
            "    from solution import check\n"
            "    assert check('good_name9') == 'OK:good_name9'\n"
        ),
    },
    {
        "task_id": "c_parcel_cost",
        "prompt": (
            "Create solution.py defining `cost(kg: float) -> float`: compute\n"
            "kg * 4.6 + 12.25; if kg > 18.0 multiply the whole amount by 1.3; return\n"
            "it rounded with round(x, 2). All four numeric constants are exact.\n\n"
            "Spelling out the identical procedure once more: every parcel pays a\n"
            "weight-proportional amount (the per-kilogram rate from the first\n"
            "sentence times the weight) plus the flat handling amount from the first\n"
            "sentence. Parcels whose weight strictly exceeds the bulky-parcel\n"
            "threshold from the first sentence have the ENTIRE amount so far — both\n"
            "the proportional part and the flat part — scaled by the bulky\n"
            "multiplier from the first sentence; parcels at exactly that weight are\n"
            "NOT scaled. The very last step is always the two-decimal rounding shown\n"
            "above, applied once, after any scaling. There are no other fees,\n"
            "discounts, thresholds or special cases beyond what the first sentence\n"
            "already states.\n"
        ),
        "starter_code": (
            "def cost(kg: float) -> float:\n"
            '    """Compute the delivery cost of a parcel by weight."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_zero_weight():\n"
            "    from solution import cost\n"
            "    assert cost(0.0) == 12.25\n"
            "\n"
            "\n"
            "def test_one_kg():\n"
            "    from solution import cost\n"
            "    assert cost(1.0) == 16.85\n"
            "\n"
            "\n"
            "def test_ten_kg():\n"
            "    from solution import cost\n"
            "    assert cost(10.0) == 58.25\n"
            "\n"
            "\n"
            "def test_no_scaling_at_exact_threshold():\n"
            "    from solution import cost\n"
            "    assert cost(18.0) == 95.05\n"
            "\n"
            "\n"
            "def test_scaling_just_above_threshold():\n"
            "    from solution import cost\n"
            "    assert cost(18.1) == 124.16\n"
            "\n"
            "\n"
            "def test_twenty_kg():\n"
            "    from solution import cost\n"
            "    assert cost(20.0) == 135.53\n"
            "\n"
            "\n"
            "def test_fractional_weight():\n"
            "    from solution import cost\n"
            "    assert cost(5.5) == 37.55\n"
            "\n"
            "\n"
            "def test_heavy_parcel():\n"
            "    from solution import cost\n"
            "    assert cost(100.0) == 613.92\n"
        ),
    },
    {
        "task_id": "c_vote_tally",
        "prompt": (
            "Create solution.py defining `tally(votes: list[str]) -> str`: count the\n"
            "exact strings 'yes' and 'no' (ignore everything else); return\n"
            "'APPROVED(y-n)' if yes >= no + 3, else 'REJECTED(y-n)', where y and n\n"
            "are the two counts.\n\n"
            "Describing the very same behaviour again for clarity: the function\n"
            "walks the list and keeps two counters, one for entries equal to the\n"
            "affirmative string from the first sentence and one for entries equal to\n"
            "the negative string from the first sentence; every other entry —\n"
            "including different capitalisations, abstentions or arbitrary text — is\n"
            "simply skipped and affects nothing. The motion passes only when the\n"
            "affirmative count beats the negative count by at least the margin\n"
            "stated in the first sentence. The returned string is the verdict word\n"
            "from the first sentence followed immediately by an opening parenthesis,\n"
            "the affirmative count, a hyphen, the negative count, and a closing\n"
            "parenthesis, with no spaces anywhere inside it.\n"
        ),
        "starter_code": (
            "def tally(votes: list[str]) -> str:\n"
            '    """Tally yes/no votes and return the verdict string."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_unanimous_approval():\n"
            "    from solution import tally\n"
            "    assert tally(['yes', 'yes', 'yes']) == 'APPROVED(3-0)'\n"
            "\n"
            "\n"
            "def test_margin_too_small():\n"
            "    from solution import tally\n"
            "    assert tally(['yes', 'yes', 'yes', 'no']) == 'REJECTED(3-1)'\n"
            "\n"
            "\n"
            "def test_margin_exactly_three():\n"
            "    from solution import tally\n"
            "    assert tally(['yes', 'yes', 'yes', 'yes', 'no']) == 'APPROVED(4-1)'\n"
            "\n"
            "\n"
            "def test_empty_vote_list():\n"
            "    from solution import tally\n"
            "    assert tally([]) == 'REJECTED(0-0)'\n"
            "\n"
            "\n"
            "def test_only_no_votes():\n"
            "    from solution import tally\n"
            "    assert tally(['no', 'no']) == 'REJECTED(0-2)'\n"
            "\n"
            "\n"
            "def test_other_strings_ignored():\n"
            "    from solution import tally\n"
            "    assert tally(['yes', 'maybe', 'yes', 'YES', 'yes']) == 'APPROVED(3-0)'\n"
            "\n"
            "\n"
            "def test_mixed_with_margin():\n"
            "    from solution import tally\n"
            "    votes = ['yes'] * 5 + ['no'] * 2\n"
            "    assert tally(votes) == 'APPROVED(5-2)'\n"
            "\n"
            "\n"
            "def test_abstain_only():\n"
            "    from solution import tally\n"
            "    assert tally(['abstain']) == 'REJECTED(0-0)'\n"
        ),
    },
    # ------------------------- ESTRATO L -------------------------
    {
        "task_id": "l_payroll_pipeline",
        "prompt": (
            "You are asked to implement a monthly payroll pipeline for a staffing\n"
            "agency. The work is split across three files that you must create in\n"
            "the workspace: two small helper files and the main entry point file\n"
            "solution.py that the tests call. Follow every numbered rule below\n"
            "exactly and in the stated order; the business constants are arbitrary\n"
            "and cannot be guessed or derived from anything else.\n\n"
            "Files and functions:\n"
            "1. tax_utils.py must define `withhold(gross: float) -> float`\n"
            "   returning gross * 0.2140 (the flat withholding rate).\n"
            "2. bonus_utils.py must define `seniority_bonus(years: int) -> float`\n"
            "   returning years * 37.25.\n"
            "3. solution.py must define\n"
            "   `net_pay(hours: float, rate: float, years: int) -> float` computed\n"
            "   in this exact order:\n"
            "   - gross = hours * rate.\n"
            "   - Overtime: if hours is STRICTLY greater than 172.0, add\n"
            "     (hours - 172.0) * rate * 0.65 to gross (at exactly 172.0 there is\n"
            "     no overtime).\n"
            "   - total = gross + seniority_bonus(years).\n"
            "   - net = total - withhold(total); the withholding applies to the\n"
            "     WHOLE total, seniority bonus included.\n"
            "   Return round(net, 2).\n"
        ),
        "starter_code": (
            "def net_pay(hours: float, rate: float, years: int) -> float:\n"
            '    """Compute the net monthly pay of an employee."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_withhold():\n"
            "    from tax_utils import withhold\n"
            "    assert withhold(100.0) == 21.4\n"
            "\n"
            "\n"
            "def test_helper_withhold_zero():\n"
            "    from tax_utils import withhold\n"
            "    assert withhold(0.0) == 0.0\n"
            "\n"
            "\n"
            "def test_helper_bonus_four_years():\n"
            "    from bonus_utils import seniority_bonus\n"
            "    assert seniority_bonus(4) == 149.0\n"
            "\n"
            "\n"
            "def test_helper_bonus_six_years():\n"
            "    from bonus_utils import seniority_bonus\n"
            "    assert seniority_bonus(6) == 223.5\n"
            "\n"
            "\n"
            "def test_regular_month():\n"
            "    from solution import net_pay\n"
            "    assert net_pay(160, 20.0, 0) == 2515.2\n"
            "\n"
            "\n"
            "def test_exact_overtime_threshold():\n"
            "    from solution import net_pay\n"
            "    assert net_pay(172, 20.0, 0) == 2703.84\n"
            "\n"
            "\n"
            "def test_overtime_no_bonus():\n"
            "    from solution import net_pay\n"
            "    assert net_pay(180, 20.0, 0) == 2911.34\n"
            "\n"
            "\n"
            "def test_overtime_with_bonus():\n"
            "    from solution import net_pay\n"
            "    assert net_pay(180, 20.0, 5) == 3057.74\n"
            "\n"
            "\n"
            "def test_fractional_rate():\n"
            "    from solution import net_pay\n"
            "    assert net_pay(100, 31.5, 2) == 2534.46\n"
            "\n"
            "\n"
            "def test_zero_hours_bonus_only():\n"
            "    from solution import net_pay\n"
            "    assert net_pay(0, 10.0, 3) == 87.84\n"
        ),
    },
    {
        "task_id": "l_loyalty_points",
        "prompt": (
            "You are asked to implement a customer loyalty points module for a\n"
            "retail chain. The work is split across three files that you must\n"
            "create in the workspace: two small helper files and the main entry\n"
            "point file solution.py that the tests call. Every threshold and\n"
            "multiplier below is an arbitrary business rule that must be followed\n"
            "exactly as written; none of them can be inferred.\n\n"
            "Files and functions:\n"
            "1. tier_utils.py must define `tier(total_spend: float) -> str`\n"
            "   returning 'GOLD' if total_spend is STRICTLY greater than 812.40,\n"
            "   otherwise 'SILVER' if STRICTLY greater than 296.70, otherwise\n"
            "   'BASE' (each boundary value belongs to the lower tier).\n"
            "2. points_utils.py must define `base_points(amount: float) -> int`\n"
            "   returning int(amount * 3.7) (truncation, not rounding).\n"
            "3. solution.py must define\n"
            "   `award(amount: float, total_spend: float) -> int` computed as:\n"
            "   - p = base_points(amount).\n"
            "   - Look up the customer's tier with tier(total_spend) and pick the\n"
            "     multiplier: 2.25 for 'GOLD', 1.4 for 'SILVER', 1.0 for 'BASE'.\n"
            "   - Return int(p * multiplier) (truncation again, never rounding).\n"
        ),
        "starter_code": (
            "def award(amount: float, total_spend: float) -> int:\n"
            '    """Compute the loyalty points awarded for a purchase."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_tier_gold():\n"
            "    from tier_utils import tier\n"
            "    assert tier(813.0) == 'GOLD'\n"
            "\n"
            "\n"
            "def test_helper_tier_gold_boundary_is_silver():\n"
            "    from tier_utils import tier\n"
            "    assert tier(812.4) == 'SILVER'\n"
            "\n"
            "\n"
            "def test_helper_tier_silver():\n"
            "    from tier_utils import tier\n"
            "    assert tier(297.0) == 'SILVER'\n"
            "\n"
            "\n"
            "def test_helper_tier_silver_boundary_is_base():\n"
            "    from tier_utils import tier\n"
            "    assert tier(296.7) == 'BASE'\n"
            "\n"
            "\n"
            "def test_helper_tier_base():\n"
            "    from tier_utils import tier\n"
            "    assert tier(100.0) == 'BASE'\n"
            "\n"
            "\n"
            "def test_helper_base_points():\n"
            "    from points_utils import base_points\n"
            "    assert base_points(10.0) == 37\n"
            "\n"
            "\n"
            "def test_helper_base_points_truncates():\n"
            "    from points_utils import base_points\n"
            "    assert base_points(25.5) == 94\n"
            "\n"
            "\n"
            "def test_award_gold():\n"
            "    from solution import award\n"
            "    assert award(10.0, 1000.0) == 83\n"
            "\n"
            "\n"
            "def test_award_silver():\n"
            "    from solution import award\n"
            "    assert award(10.0, 500.0) == 51\n"
            "\n"
            "\n"
            "def test_award_base():\n"
            "    from solution import award\n"
            "    assert award(10.0, 50.0) == 37\n"
            "\n"
            "\n"
            "def test_award_gold_large():\n"
            "    from solution import award\n"
            "    assert award(100.0, 900.0) == 832\n"
            "\n"
            "\n"
            "def test_award_zero_amount():\n"
            "    from solution import award\n"
            "    assert award(0.0, 2000.0) == 0\n"
        ),
    },
    {
        "task_id": "l_shipping_batch",
        "prompt": (
            "You are asked to implement a batch shipping cost calculator for a\n"
            "warehouse operator. The work is split across three files that you\n"
            "must create in the workspace: two small helper files and the main\n"
            "entry point file solution.py that the tests call. Read the whole\n"
            "specification before writing code; the rates and thresholds are\n"
            "arbitrary and matter down to the last digit.\n\n"
            "Files and functions:\n"
            "1. box_utils.py must define\n"
            "   `volumetric(l: float, w: float, h: float) -> float` returning\n"
            "   (l * w * h) / 4820.0.\n"
            "2. rate_utils.py must define `zone_rate(zone: str) -> float`\n"
            "   returning 5.85 for zone 'A', 9.15 for zone 'B' and 13.4 for\n"
            "   zone 'C'.\n"
            "3. solution.py must define\n"
            "   `batch_cost(boxes: list[tuple], zone: str) -> float` where each\n"
            "   box is a tuple (l, w, h, actual_kg), computed in this exact order:\n"
            "   - The chargeable weight of a box is\n"
            "     max(actual_kg, volumetric(l, w, h)).\n"
            "   - cost = (sum of all chargeable weights) * zone_rate(zone) plus a\n"
            "     flat handling fee of 27.9.\n"
            "   - Bulk discount: if the batch has STRICTLY more than 4 boxes,\n"
            "     multiply the whole cost by 0.94 (at exactly 4 boxes there is no\n"
            "     discount).\n"
            "   - Return round(cost, 2).\n"
        ),
        "starter_code": (
            "def batch_cost(boxes: list[tuple], zone: str) -> float:\n"
            '    """Compute the shipping cost of a batch of boxes."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_volumetric_unit():\n"
            "    from box_utils import volumetric\n"
            "    assert volumetric(2410, 2, 1) == 1.0\n"
            "\n"
            "\n"
            "def test_helper_volumetric_zero():\n"
            "    from box_utils import volumetric\n"
            "    assert volumetric(0, 10, 10) == 0.0\n"
            "\n"
            "\n"
            "def test_helper_zone_a():\n"
            "    from rate_utils import zone_rate\n"
            "    assert zone_rate('A') == 5.85\n"
            "\n"
            "\n"
            "def test_helper_zone_b():\n"
            "    from rate_utils import zone_rate\n"
            "    assert zone_rate('B') == 9.15\n"
            "\n"
            "\n"
            "def test_helper_zone_c():\n"
            "    from rate_utils import zone_rate\n"
            "    assert zone_rate('C') == 13.4\n"
            "\n"
            "\n"
            "def test_single_box_actual_weight_zone_a():\n"
            "    from solution import batch_cost\n"
            "    assert batch_cost([(10, 10, 10, 2.0)], 'A') == 39.6\n"
            "\n"
            "\n"
            "def test_single_box_actual_weight_zone_c():\n"
            "    from solution import batch_cost\n"
            "    assert batch_cost([(10, 10, 10, 2.0)], 'C') == 54.7\n"
            "\n"
            "\n"
            "def test_volumetric_weight_wins():\n"
            "    from solution import batch_cost\n"
            "    assert batch_cost([(50, 40, 30, 1.0)], 'B') == 141.8\n"
            "\n"
            "\n"
            "def test_two_boxes_no_discount():\n"
            "    from solution import batch_cost\n"
            "    assert batch_cost([(10, 10, 10, 3.0), (20, 20, 20, 1.0)], 'A') == 55.16\n"
            "\n"
            "\n"
            "def test_five_boxes_bulk_discount():\n"
            "    from solution import batch_cost\n"
            "    assert batch_cost([(10, 10, 10, 1.0)] * 5, 'A') == 53.72\n"
            "\n"
            "\n"
            "def test_mixed_batch_zone_c():\n"
            "    from solution import batch_cost\n"
            "    assert batch_cost([(50, 40, 30, 20.0), (10, 10, 10, 0.5)], 'C') == 302.6\n"
        ),
    },
    {
        "task_id": "l_rental_invoice",
        "prompt": (
            "You are asked to implement an invoice generator for a car rental\n"
            "company. The work is split across three files that you must create in\n"
            "the workspace: two small helper files and the main entry point file\n"
            "solution.py that the tests call. Apply the charges below in exactly\n"
            "the order given; every rate is an arbitrary business constant that\n"
            "cannot be derived from anything else in the code.\n\n"
            "Files and functions:\n"
            "1. fuel_utils.py must define `fuel_charge(liters: float) -> float`\n"
            "   returning liters * 7.35.\n"
            "2. insure_utils.py must define `insurance(days: int) -> float`\n"
            "   returning days * 12.60.\n"
            "3. solution.py must define\n"
            "   `invoice(days: int, km: float, liters: float, insured: bool) ->\n"
            "   float` computed in this exact order:\n"
            "   - total = days * 44.90 + km * 0.37.\n"
            "   - Add fuel_charge(liters).\n"
            "   - If insured is True, add insurance(days).\n"
            "   - Long-distance penalty: if km is STRICTLY greater than 950, add a\n"
            "     flat 88.0 (at exactly 950 kilometres there is no penalty).\n"
            "   - Return round(total, 2).\n"
        ),
        "starter_code": (
            "def invoice(days: int, km: float, liters: float, insured: bool) -> float:\n"
            '    """Compute the total rental invoice amount."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_fuel_charge():\n"
            "    from fuel_utils import fuel_charge\n"
            "    assert fuel_charge(10.0) == 73.5\n"
            "\n"
            "\n"
            "def test_helper_fuel_charge_zero():\n"
            "    from fuel_utils import fuel_charge\n"
            "    assert fuel_charge(0.0) == 0.0\n"
            "\n"
            "\n"
            "def test_helper_insurance_three_days():\n"
            "    from insure_utils import insurance\n"
            "    assert insurance(3) == 37.8\n"
            "\n"
            "\n"
            "def test_helper_insurance_seven_days():\n"
            "    from insure_utils import insurance\n"
            "    assert insurance(7) == 88.2\n"
            "\n"
            "\n"
            "def test_basic_rental_uninsured():\n"
            "    from solution import invoice\n"
            "    assert invoice(3, 100, 0.0, False) == 171.7\n"
            "\n"
            "\n"
            "def test_basic_rental_insured():\n"
            "    from solution import invoice\n"
            "    assert invoice(3, 100, 0.0, True) == 209.5\n"
            "\n"
            "\n"
            "def test_no_penalty_at_exact_km_threshold():\n"
            "    from solution import invoice\n"
            "    assert invoice(5, 950, 12.5, False) == 667.88\n"
            "\n"
            "\n"
            "def test_penalty_just_above_km_threshold():\n"
            "    from solution import invoice\n"
            "    assert invoice(5, 951, 12.5, False) == 756.25\n"
            "\n"
            "\n"
            "def test_one_day_with_fuel_and_insurance():\n"
            "    from solution import invoice\n"
            "    assert invoice(1, 0, 4.2, True) == 88.37\n"
            "\n"
            "\n"
            "def test_long_trip_everything():\n"
            "    from solution import invoice\n"
            "    assert invoice(10, 1200, 30.0, True) == 1327.5\n"
        ),
    },
    {
        "task_id": "l_grade_report",
        "prompt": (
            "You are asked to implement a final grade reporting module for a\n"
            "university course. The work is split across three files that you must\n"
            "create in the workspace: two small helper files and the main entry\n"
            "point file solution.py that the tests call. The weights, the curve\n"
            "and the letter boundaries below are arbitrary and must be applied in\n"
            "the exact order stated; do not reorder any step.\n\n"
            "Files and functions:\n"
            "1. score_utils.py must define `weighted(exam: float, hw: float) ->\n"
            "   float` returning exam * 0.62 + hw * 0.38.\n"
            "2. curve_utils.py must define `curve(score: float) -> float`\n"
            "   returning min(score + 4.7, 100.0).\n"
            "3. solution.py must define\n"
            "   `report(exam: float, hw: float, attendance: float) -> str`:\n"
            "   - s = curve(weighted(exam, hw)).\n"
            "   - Attendance penalty: if attendance < 0.75, multiply s by 0.85\n"
            "     (the penalty is applied AFTER the curve).\n"
            "   - Letter grade: 'A' if s >= 91.5, else 'B' if s >= 78.3, else 'C'\n"
            "     if s >= 62.1, else 'F'.\n"
            "   - Return the string f\"{letter}:{round(s, 2)}\" — the letter, a\n"
            "     colon, then the rounded score.\n"
        ),
        "starter_code": (
            "def report(exam: float, hw: float, attendance: float) -> str:\n"
            '    """Compute the final grade report string for a student."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_weighted():\n"
            "    from score_utils import weighted\n"
            "    assert round(weighted(80, 90), 2) == 83.8\n"
            "\n"
            "\n"
            "def test_helper_weighted_perfect():\n"
            "    from score_utils import weighted\n"
            "    assert weighted(100, 100) == 100.0\n"
            "\n"
            "\n"
            "def test_helper_curve_adds():\n"
            "    from curve_utils import curve\n"
            "    assert curve(50.0) == 54.7\n"
            "\n"
            "\n"
            "def test_helper_curve_caps_at_hundred():\n"
            "    from curve_utils import curve\n"
            "    assert curve(97.0) == 100.0\n"
            "\n"
            "\n"
            "def test_report_a():\n"
            "    from solution import report\n"
            "    assert report(90, 95, 1.0) == 'A:96.6'\n"
            "\n"
            "\n"
            "def test_report_b():\n"
            "    from solution import report\n"
            "    assert report(80, 70, 0.9) == 'B:80.9'\n"
            "\n"
            "\n"
            "def test_report_c():\n"
            "    from solution import report\n"
            "    assert report(60, 60, 0.8) == 'C:64.7'\n"
            "\n"
            "\n"
            "def test_report_f():\n"
            "    from solution import report\n"
            "    assert report(40, 30, 1.0) == 'F:40.9'\n"
            "\n"
            "\n"
            "def test_attendance_penalty_drops_grade():\n"
            "    from solution import report\n"
            "    assert report(90, 95, 0.5) == 'B:82.11'\n"
            "\n"
            "\n"
            "def test_perfect_score():\n"
            "    from solution import report\n"
            "    assert report(100, 100, 1.0) == 'A:100.0'\n"
            "\n"
            "\n"
            "def test_attendance_just_below_threshold():\n"
            "    from solution import report\n"
            "    assert report(75, 80, 0.74) == 'C:69.36'\n"
        ),
    },
    {
        "task_id": "l_order_validator",
        "prompt": (
            "You are asked to implement an order validation routine for a\n"
            "wholesale ordering API. The work is split across three files that you\n"
            "must create in the workspace: two small helper files and the main\n"
            "entry point file solution.py that the tests call. The checks must run\n"
            "in the exact order listed below and each distinct failure returns its\n"
            "own specific error code; returning the right code for the right\n"
            "failure is part of the contract.\n\n"
            "Files and functions:\n"
            "1. sku_utils.py must define `valid_sku(s) -> bool` returning True iff\n"
            "   s is a string that starts with the prefix 'ZQ-', has total length\n"
            "   7, and the 4 characters after the prefix are all digits.\n"
            "2. qty_utils.py must define `qty_in_range(q: int) -> bool` returning\n"
            "   True iff 1 <= q <= 46.\n"
            "3. solution.py must define `validate(order: dict) -> str` running\n"
            "   these checks in this exact order and returning at the FIRST\n"
            "   failure:\n"
            "   - if the key 'sku' is missing from order, return 'ERR_41';\n"
            "   - if valid_sku(order['sku']) is False, return 'ERR_17';\n"
            "   - if the key 'qty' is missing from order, return 'ERR_58';\n"
            "   - if qty_in_range(order['qty']) is False, return 'ERR_23';\n"
            "   - if order.get('express') is truthy AND order['qty'] > 30, return\n"
            "     'ERR_66' (express orders are capped);\n"
            "   - otherwise return 'OK:' immediately followed by the sku.\n"
        ),
        "starter_code": (
            "def validate(order: dict) -> str:\n"
            '    """Validate a wholesale order and return a status code."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_valid_sku_accepts():\n"
            "    from sku_utils import valid_sku\n"
            "    assert valid_sku('ZQ-1234') is True\n"
            "\n"
            "\n"
            "def test_helper_valid_sku_wrong_prefix():\n"
            "    from sku_utils import valid_sku\n"
            "    assert valid_sku('AB-1234') is False\n"
            "\n"
            "\n"
            "def test_helper_valid_sku_non_digits():\n"
            "    from sku_utils import valid_sku\n"
            "    assert valid_sku('ZQ-12ab') is False\n"
            "\n"
            "\n"
            "def test_helper_qty_in_range_bounds():\n"
            "    from qty_utils import qty_in_range\n"
            "    assert qty_in_range(1) is True and qty_in_range(46) is True\n"
            "\n"
            "\n"
            "def test_helper_qty_out_of_range():\n"
            "    from qty_utils import qty_in_range\n"
            "    assert qty_in_range(0) is False and qty_in_range(47) is False\n"
            "\n"
            "\n"
            "def test_missing_sku():\n"
            "    from solution import validate\n"
            "    assert validate({}) == 'ERR_41'\n"
            "\n"
            "\n"
            "def test_invalid_sku():\n"
            "    from solution import validate\n"
            "    assert validate({'sku': 'AB-1234'}) == 'ERR_17'\n"
            "\n"
            "\n"
            "def test_missing_qty():\n"
            "    from solution import validate\n"
            "    assert validate({'sku': 'ZQ-1234'}) == 'ERR_58'\n"
            "\n"
            "\n"
            "def test_qty_too_low():\n"
            "    from solution import validate\n"
            "    assert validate({'sku': 'ZQ-1234', 'qty': 0}) == 'ERR_23'\n"
            "\n"
            "\n"
            "def test_qty_too_high():\n"
            "    from solution import validate\n"
            "    assert validate({'sku': 'ZQ-1234', 'qty': 47}) == 'ERR_23'\n"
            "\n"
            "\n"
            "def test_express_over_cap():\n"
            "    from solution import validate\n"
            "    assert validate({'sku': 'ZQ-1234', 'qty': 31, 'express': True}) == 'ERR_66'\n"
            "\n"
            "\n"
            "def test_express_at_cap_ok():\n"
            "    from solution import validate\n"
            "    assert validate({'sku': 'ZQ-1234', 'qty': 30, 'express': True}) == 'OK:ZQ-1234'\n"
            "\n"
            "\n"
            "def test_valid_non_express():\n"
            "    from solution import validate\n"
            "    assert validate({'sku': 'ZQ-1234', 'qty': 31}) == 'OK:ZQ-1234'\n"
        ),
    },
    {
        "task_id": "l_log_parser",
        "prompt": (
            "You are asked to implement a log severity scorer for a monitoring\n"
            "backend. The work is split across three files that you must create in\n"
            "the workspace: two small helper files and the main entry point file\n"
            "solution.py that the tests call. The parser must apply every skip\n"
            "rule and every numeric constant below exactly; malformed input is\n"
            "silently ignored, never an exception.\n\n"
            "Files and functions:\n"
            "1. level_utils.py must define `level_weight(level: str) -> float`\n"
            "   returning 0.5 for 'DEBUG', 3.25 for 'WARN', 8.75 for 'FATAL' and\n"
            "   0.0 for anything else.\n"
            "2. ts_utils.py must define `in_window(ts: int) -> bool` returning\n"
            "   True iff 1200 <= ts <= 8600 (both ends inclusive).\n"
            "3. solution.py must define `severity(lines: list[str]) -> float`.\n"
            "   Each line should have the form 'ts|LEVEL|message'. For each line,\n"
            "   in order:\n"
            "   - split on '|'; if there are not exactly 3 parts, skip the line;\n"
            "   - if the first part is not a valid integer, skip the line;\n"
            "   - if in_window(ts) is False, skip the line;\n"
            "   - if level_weight(level) is 0.0, skip the line;\n"
            "   - otherwise add the weight to a running total.\n"
            "   After processing all lines, if at least one counted line had level\n"
            "   'FATAL', multiply the total by 1.9. Return round(total, 2).\n"
        ),
        "starter_code": (
            "def severity(lines: list[str]) -> float:\n"
            '    """Compute the aggregate severity score of a log window."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_level_weight_warn():\n"
            "    from level_utils import level_weight\n"
            "    assert level_weight('WARN') == 3.25\n"
            "\n"
            "\n"
            "def test_helper_level_weight_unknown():\n"
            "    from level_utils import level_weight\n"
            "    assert level_weight('INFO') == 0.0\n"
            "\n"
            "\n"
            "def test_helper_window_inclusive_ends():\n"
            "    from ts_utils import in_window\n"
            "    assert in_window(1200) is True and in_window(8600) is True\n"
            "\n"
            "\n"
            "def test_helper_window_outside():\n"
            "    from ts_utils import in_window\n"
            "    assert in_window(1199) is False and in_window(8601) is False\n"
            "\n"
            "\n"
            "def test_empty_log():\n"
            "    from solution import severity\n"
            "    assert severity([]) == 0.0\n"
            "\n"
            "\n"
            "def test_single_debug():\n"
            "    from solution import severity\n"
            "    assert severity(['2000|DEBUG|x']) == 0.5\n"
            "\n"
            "\n"
            "def test_warn_plus_debug():\n"
            "    from solution import severity\n"
            "    assert severity(['2000|WARN|x', '3000|DEBUG|y']) == 3.75\n"
            "\n"
            "\n"
            "def test_fatal_multiplier():\n"
            "    from solution import severity\n"
            "    assert severity(['2000|FATAL|boom']) == 16.62\n"
            "\n"
            "\n"
            "def test_fatal_multiplies_whole_total():\n"
            "    from solution import severity\n"
            "    assert severity(['2000|WARN|x', '3000|FATAL|y']) == 22.8\n"
            "\n"
            "\n"
            "def test_fatal_outside_window_no_multiplier():\n"
            "    from solution import severity\n"
            "    assert severity(['100|FATAL|early', '2000|WARN|x']) == 3.25\n"
            "\n"
            "\n"
            "def test_malformed_lines_skipped():\n"
            "    from solution import severity\n"
            "    assert severity(['2000|WARN', 'bad line', '3000|DEBUG|ok']) == 0.5\n"
            "\n"
            "\n"
            "def test_non_integer_timestamp_skipped():\n"
            "    from solution import severity\n"
            "    assert severity(['abc|WARN|x', '2500|DEBUG|y']) == 0.5\n"
            "\n"
            "\n"
            "def test_unknown_level_skipped():\n"
            "    from solution import severity\n"
            "    assert severity(['2000|INFO|ignored', '2500|WARN|x']) == 3.25\n"
        ),
    },
    {
        "task_id": "l_vending_machine",
        "prompt": (
            "You are asked to implement the control loop of a token-operated\n"
            "vending machine. The work is split across three files that you must\n"
            "create in the workspace: two small helper files and the main entry\n"
            "point file solution.py that the tests call. The machine processes an\n"
            "event list and emits one output string per event; token values,\n"
            "prices and error codes are all arbitrary constants defined below.\n\n"
            "Files and functions:\n"
            "1. coin_utils.py must define `coin_value(code: str) -> float`\n"
            "   returning 0.35 for 'T1', 1.15 for 'T2', 2.6 for 'T5' and 0.0\n"
            "   otherwise.\n"
            "2. price_utils.py must define `price(item: str) -> float` returning\n"
            "   3.05 for 'cola' and 1.85 for 'chips'.\n"
            "3. solution.py must define `run(events: list[str]) -> list[str]`.\n"
            "   Credit starts at 0.0. For each event, in order:\n"
            "   - 'T1', 'T2' or 'T5': set credit = round(credit + coin_value, 2)\n"
            "     and append f'CREDIT:{credit}';\n"
            "   - 'SEL:<item>': if credit >= price(item), append\n"
            "     f'VEND:{item}:{change}' where change = round(credit - price, 2)\n"
            "     and reset credit to 0.0; otherwise append 'ERR_LOW' and keep the\n"
            "     credit;\n"
            "   - 'CANCEL': append f'REFUND:{credit}' and reset credit to 0.0;\n"
            "   - any other event: append 'ERR_EVT' (credit unchanged).\n"
            "   Numbers are formatted with Python's default float formatting.\n"
        ),
        "starter_code": (
            "def run(events: list[str]) -> list[str]:\n"
            '    """Process vending machine events and return the output log."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_coin_values():\n"
            "    from coin_utils import coin_value\n"
            "    assert coin_value('T2') == 1.15\n"
            "\n"
            "\n"
            "def test_helper_coin_unknown():\n"
            "    from coin_utils import coin_value\n"
            "    assert coin_value('T9') == 0.0\n"
            "\n"
            "\n"
            "def test_helper_price_chips():\n"
            "    from price_utils import price\n"
            "    assert price('chips') == 1.85\n"
            "\n"
            "\n"
            "def test_single_token():\n"
            "    from solution import run\n"
            "    assert run(['T1']) == ['CREDIT:0.35']\n"
            "\n"
            "\n"
            "def test_credit_accumulates():\n"
            "    from solution import run\n"
            "    assert run(['T2', 'T2']) == ['CREDIT:1.15', 'CREDIT:2.3']\n"
            "\n"
            "\n"
            "def test_insufficient_credit_keeps_credit():\n"
            "    from solution import run\n"
            "    assert run(['T2', 'SEL:chips']) == ['CREDIT:1.15', 'ERR_LOW']\n"
            "\n"
            "\n"
            "def test_cola_needs_more_than_small_tokens():\n"
            "    from solution import run\n"
            "    assert run(['T5', 'T1', 'SEL:cola']) == ['CREDIT:2.6', 'CREDIT:2.95', 'ERR_LOW']\n"
            "\n"
            "\n"
            "def test_cancel_refunds_credit():\n"
            "    from solution import run\n"
            "    assert run(['T2', 'CANCEL']) == ['CREDIT:1.15', 'REFUND:1.15']\n"
            "\n"
            "\n"
            "def test_vend_resets_credit():\n"
            "    from solution import run\n"
            "    assert run(['T5', 'SEL:chips', 'SEL:chips']) == ['CREDIT:2.6', 'VEND:chips:0.75', 'ERR_LOW']\n"
            "\n"
            "\n"
            "def test_unknown_event():\n"
            "    from solution import run\n"
            "    assert run(['XX']) == ['ERR_EVT']\n"
            "\n"
            "\n"
            "def test_full_session():\n"
            "    from solution import run\n"
            "    assert run(['T2', 'T2', 'T1', 'SEL:cola', 'T2', 'SEL:chips']) == [\n"
            "        'CREDIT:1.15', 'CREDIT:2.3', 'CREDIT:2.65', 'ERR_LOW',\n"
            "        'CREDIT:3.8', 'VEND:chips:1.95',\n"
            "    ]\n"
        ),
    },
    {
        "task_id": "l_door_controller",
        "prompt": (
            "You are asked to implement the state machine of a secure door\n"
            "controller. The work is split across three files that you must create\n"
            "in the workspace: two small helper files and the main entry point\n"
            "file solution.py that the tests call. The controller consumes a list\n"
            "of event tuples and emits one output string per event; every state\n"
            "transition rule below is mandatory and order matters.\n\n"
            "Files and functions:\n"
            "1. badge_utils.py must define `badge_ok(code) -> bool` returning True\n"
            "   iff code is a string that starts with 'BX' and has total length 6.\n"
            "2. alarm_utils.py must define `alarm_after(fails: int) -> bool`\n"
            "   returning True iff fails >= 4.\n"
            "3. solution.py must define `control(events: list[tuple]) -> list[str]`.\n"
            "   States: 'LOCKED' (initial), 'OPEN', 'ALARM'. A failed-badge\n"
            "   counter starts at 0. For each event tuple, in order:\n"
            "   - ('force',): from ANY state go to ALARM and append 'ALARM_ON'.\n"
            "   - In ALARM, ('reset', pin): if pin == '7359' go to LOCKED, reset\n"
            "     the counter to 0 and append 'RESET_OK'; otherwise append\n"
            "     'ERR_PIN'. Any other event in ALARM appends 'ERR_STATE'.\n"
            "   - In LOCKED, ('badge', code): if badge_ok(code), go to OPEN, reset\n"
            "     the counter to 0 and append 'OPENED'; otherwise increment the\n"
            "     counter and, if alarm_after(counter), go to ALARM and append\n"
            "     'ALARM_ON', else append 'DENIED'. Any other event in LOCKED\n"
            "     appends 'ERR_STATE'.\n"
            "   - In OPEN, ('close',): go to LOCKED and append 'CLOSED'. Any other\n"
            "     event in OPEN appends 'ERR_STATE'.\n"
        ),
        "starter_code": (
            "def control(events: list[tuple]) -> list[str]:\n"
            '    """Run the door controller state machine over an event list."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_badge_ok_accepts():\n"
            "    from badge_utils import badge_ok\n"
            "    assert badge_ok('BX1234') is True\n"
            "\n"
            "\n"
            "def test_helper_badge_ok_rejects():\n"
            "    from badge_utils import badge_ok\n"
            "    assert badge_ok('AX1234') is False and badge_ok('BX12') is False\n"
            "\n"
            "\n"
            "def test_helper_alarm_after():\n"
            "    from alarm_utils import alarm_after\n"
            "    assert alarm_after(3) is False and alarm_after(4) is True\n"
            "\n"
            "\n"
            "def test_open_with_valid_badge():\n"
            "    from solution import control\n"
            "    assert control([('badge', 'BX1234')]) == ['OPENED']\n"
            "\n"
            "\n"
            "def test_denied_with_invalid_badge():\n"
            "    from solution import control\n"
            "    assert control([('badge', 'XX0000')]) == ['DENIED']\n"
            "\n"
            "\n"
            "def test_open_then_close():\n"
            "    from solution import control\n"
            "    assert control([('badge', 'BX1234'), ('close',)]) == ['OPENED', 'CLOSED']\n"
            "\n"
            "\n"
            "def test_badge_while_open_is_error():\n"
            "    from solution import control\n"
            "    assert control([('badge', 'BX1234'), ('badge', 'BX9999')]) == ['OPENED', 'ERR_STATE']\n"
            "\n"
            "\n"
            "def test_close_while_locked_is_error():\n"
            "    from solution import control\n"
            "    assert control([('close',)]) == ['ERR_STATE']\n"
            "\n"
            "\n"
            "def test_repeated_failures_trigger_alarm():\n"
            "    from solution import control\n"
            "    events = [('badge', 'bad')] * 4\n"
            "    assert control(events) == ['DENIED', 'DENIED', 'DENIED', 'ALARM_ON']\n"
            "\n"
            "\n"
            "def test_force_locks_everything():\n"
            "    from solution import control\n"
            "    assert control([('force',), ('badge', 'BX1234')]) == ['ALARM_ON', 'ERR_STATE']\n"
            "\n"
            "\n"
            "def test_reset_with_correct_pin():\n"
            "    from solution import control\n"
            "    events = [('force',), ('reset', '7359'), ('badge', 'BX1234')]\n"
            "    assert control(events) == ['ALARM_ON', 'RESET_OK', 'OPENED']\n"
            "\n"
            "\n"
            "def test_reset_with_wrong_pin():\n"
            "    from solution import control\n"
            "    assert control([('force',), ('reset', '0000')]) == ['ALARM_ON', 'ERR_PIN']\n"
            "\n"
            "\n"
            "def test_success_resets_fail_counter():\n"
            "    from solution import control\n"
            "    events = [('badge', 'bad')] * 3 + [\n"
            "        ('badge', 'BX1234'), ('close',), ('badge', 'bad'),\n"
            "    ]\n"
            "    assert control(events) == [\n"
            "        'DENIED', 'DENIED', 'DENIED', 'OPENED', 'CLOSED', 'DENIED',\n"
            "    ]\n"
        ),
    },
    {
        "task_id": "l_discount_chain",
        "prompt": (
            "You are asked to implement the checkout discount chain of an online\n"
            "store. The work is split across three files that you must create in\n"
            "the workspace: two small helper files and the main entry point file\n"
            "solution.py that the tests call. The chain applies several\n"
            "adjustments to a subtotal and the ORDER of the steps is part of the\n"
            "specification — swapping any two steps produces wrong totals.\n\n"
            "Files and functions:\n"
            "1. coupon_utils.py must define `coupon_pct(code: str) -> float`\n"
            "   returning 0.14 for 'VX9', 0.23 for 'KJ4' and 0.0 for any other\n"
            "   code.\n"
            "2. member_utils.py must define `member_rate(level: str) -> float`\n"
            "   returning 0.06 for 'plus', 0.11 for 'max' and 0.0 otherwise.\n"
            "3. solution.py must define\n"
            "   `final_price(subtotal: float, code: str, level: str) -> float`\n"
            "   computed in this exact order:\n"
            "   - Step 1: apply the coupon: p = subtotal * (1 - coupon_pct(code)).\n"
            "   - Step 2: apply the membership: p = p * (1 - member_rate(level)).\n"
            "   - Step 3: big-cart rebate: if p is STRICTLY greater than 480.0\n"
            "     AFTER the two discounts, subtract a flat 25.5.\n"
            "   - Step 4: add a handling fee of 3.95.\n"
            "   - Step 5: return round(p, 2).\n"
        ),
        "starter_code": (
            "def final_price(subtotal: float, code: str, level: str) -> float:\n"
            '    """Compute the final checkout price after the discount chain."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_helper_coupon_known_codes():\n"
            "    from coupon_utils import coupon_pct\n"
            "    assert coupon_pct('VX9') == 0.14 and coupon_pct('KJ4') == 0.23\n"
            "\n"
            "\n"
            "def test_helper_coupon_unknown_code():\n"
            "    from coupon_utils import coupon_pct\n"
            "    assert coupon_pct('ZZ0') == 0.0\n"
            "\n"
            "\n"
            "def test_helper_member_rates():\n"
            "    from member_utils import member_rate\n"
            "    assert member_rate('plus') == 0.06 and member_rate('max') == 0.11\n"
            "\n"
            "\n"
            "def test_helper_member_unknown_level():\n"
            "    from member_utils import member_rate\n"
            "    assert member_rate('none') == 0.0\n"
            "\n"
            "\n"
            "def test_no_discounts():\n"
            "    from solution import final_price\n"
            "    assert final_price(100.0, 'none', 'none') == 103.95\n"
            "\n"
            "\n"
            "def test_coupon_only():\n"
            "    from solution import final_price\n"
            "    assert final_price(100.0, 'VX9', 'none') == 89.95\n"
            "\n"
            "\n"
            "def test_coupon_and_membership():\n"
            "    from solution import final_price\n"
            "    assert final_price(100.0, 'KJ4', 'plus') == 76.33\n"
            "\n"
            "\n"
            "def test_big_cart_rebate_applies():\n"
            "    from solution import final_price\n"
            "    assert final_price(600.0, 'none', 'none') == 578.45\n"
            "\n"
            "\n"
            "def test_discounts_can_avoid_rebate():\n"
            "    from solution import final_price\n"
            "    assert final_price(600.0, 'KJ4', 'max') == 415.13\n"
            "\n"
            "\n"
            "def test_rebate_checked_after_discounts():\n"
            "    from solution import final_price\n"
            "    assert final_price(558.2, 'VX9', 'none') == 458.5\n"
            "\n"
            "\n"
            "def test_everything_combined():\n"
            "    from solution import final_price\n"
            "    assert final_price(700.0, 'VX9', 'max') == 514.23\n"
            "\n"
            "\n"
            "def test_zero_subtotal():\n"
            "    from solution import final_price\n"
            "    assert final_price(0.0, 'KJ4', 'max') == 3.95\n"
        ),
    },
]

STRATA: dict[str, str] = {
    "s_freight_quote": "S",
    "s_ticket_pricer": "S",
    "s_sensor_alarm": "S",
    "s_commission_calc": "S",
    "s_energy_bill": "S",
    "c_temp_label": "C",
    "c_late_fee": "C",
    "c_username_check": "C",
    "c_parcel_cost": "C",
    "c_vote_tally": "C",
    "l_payroll_pipeline": "L",
    "l_loyalty_points": "L",
    "l_shipping_batch": "L",
    "l_rental_invoice": "L",
    "l_grade_report": "L",
    "l_order_validator": "L",
    "l_log_parser": "L",
    "l_vending_machine": "L",
    "l_door_controller": "L",
    "l_discount_chain": "L",
}

CRITICAL_CONSTANTS: dict[str, list[str]] = {
    "s_freight_quote": ["14.75", "3.85", "22.5", "1.12", "1.45"],
    "s_ticket_pricer": ["48.20", "0.35", "0.55", "4.15", "6.60"],
    "s_sensor_alarm": ["71.4", "33.8", "1.65", "4.35", "15.9", "1.15", "0.25", "8.2"],
    "s_commission_calc": ["0.083", "0.047", "5400", "9100", "175.0", "62.5"],
    "s_energy_bill": ["0.6175", "21.45", "240", "0.29", "0.93"],
    "c_temp_label": ["8.5", "27.0", "39.5", "'COLD'", "'MILD'", "'HOT'"],
    "c_late_fee": ["2.75", "8.0", "55.0", "30"],
    "c_username_check": ["'ERR_LEN'", "'ERR_CHAR'", "'OK:'", "5", "14"],
    "c_parcel_cost": ["4.6", "12.25", "18.0", "1.3"],
    "c_vote_tally": ["'yes'", "'no'", "'APPROVED", "'REJECTED", "+ 3"],
    "l_payroll_pipeline": ["0.2140", "37.25", "172.0", "0.65"],
    "l_loyalty_points": ["812.40", "296.70", "3.7", "2.25", "1.4"],
    "l_shipping_batch": ["4820.0", "5.85", "9.15", "13.4", "27.9", "0.94"],
    "l_rental_invoice": ["7.35", "12.60", "44.90", "0.37", "950", "88.0"],
    "l_grade_report": ["0.62", "0.38", "4.7", "0.75", "0.85", "91.5", "78.3", "62.1"],
    "l_order_validator": [
        "'ZQ-'",
        "46",
        "30",
        "'ERR_41'",
        "'ERR_17'",
        "'ERR_58'",
        "'ERR_23'",
        "'ERR_66'",
        "'OK:'",
    ],
    "l_log_parser": ["0.5", "3.25", "8.75", "1200", "8600", "1.9"],
    "l_vending_machine": [
        "0.35",
        "1.15",
        "2.6",
        "3.05",
        "1.85",
        "'ERR_LOW'",
        "'ERR_EVT'",
    ],
    "l_door_controller": ["'BX'", "6", "4", "'7359'", "'ERR_PIN'", "'ERR_STATE'"],
    "l_discount_chain": ["0.14", "0.23", "0.06", "0.11", "480.0", "25.5", "3.95"],
}


def get_task(task_id: str) -> dict:
    for task in TASKS:
        if task["task_id"] == task_id:
            return task
    raise KeyError(task_id)
