"""Pool fixo de 10 tasks v2 para o Teste 1 (summarize vs keep context).

Desenho: cada prompt tem >600 chars; os primeiros 240 chars contêm apenas a
apresentação genérica (arquivo, nome da função, propósito). Todas as constantes
arbitrárias críticas (thresholds, taxas, códigos de erro, formatos) aparecem
APÓS o char 240 e não são recuperáveis de nenhum arquivo do workspace — se o
summarize truncar o enunciado, o agente perde essas constantes e os testes que
as cobrem falham (reward parcial, não tudo-ou-nada).

Tasks multi-arquivo: o starter é gravado só em solution.py; o enunciado instrui
a criar os demais arquivos. Os test_codes dessas tasks importam DENTRO das
funções de teste para que arquivos ausentes causem falhas individuais (reward
gradual) em vez de erro de coleta.
"""

TASKS: list[dict] = [
    {
        "task_id": "invoice_pricing",
        "prompt": (
            "You are asked to implement a small invoicing module for an online store.\n"
            "The work is split across two files that you must create in the workspace:\n"
            "a low-level pricing helper file and the main entry point file solution.py\n"
            "that the tests call. Read every rule below carefully, since the exact\n"
            "numeric business constants matter and are not derivable from the code.\n\n"
            "Files and functions:\n"
            "1. pricing.py must define `line_total(qty: int, unit_price: float) -> float`\n"
            "   returning `round(qty * unit_price, 2)`.\n"
            "2. solution.py must define\n"
            "   `invoice_total(items: list[tuple[int, float]], vip: bool) -> float` where\n"
            "   each item is a (qty, unit_price) tuple. Compute the subtotal by summing\n"
            "   line_total over all items, then apply, in this exact order:\n"
            "   - Discount: if the subtotal is STRICTLY greater than 250.00, reduce it\n"
            "     by 7.35% (multiply by 0.9265). At exactly 250.00 there is no discount.\n"
            "   - Shipping: if the amount after the discount step is at least 180.50,\n"
            "     shipping is free; otherwise add a flat fee of 12.90.\n"
            "   - VIP: if vip is True, multiply the grand total by 0.88 at the very end.\n"
            "   Return the final amount rounded to 2 decimal places with round(x, 2).\n"
        ),
        "starter_code": (
            "def invoice_total(items: list[tuple[int, float]], vip: bool) -> float:\n"
            '    """Compute the invoice grand total for a list of (qty, unit_price) items."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_pricing_line_total():\n"
            "    from pricing import line_total\n"
            "    assert line_total(3, 2.5) == 7.5\n"
            "\n"
            "\n"
            "def test_small_order_pays_shipping():\n"
            "    from solution import invoice_total\n"
            "    assert invoice_total([(2, 10.0)], False) == 32.9\n"
            "\n"
            "\n"
            "def test_discount_applies_above_threshold():\n"
            "    from solution import invoice_total\n"
            "    assert invoice_total([(1, 300.0)], False) == 277.95\n"
            "\n"
            "\n"
            "def test_no_discount_at_exact_threshold():\n"
            "    from solution import invoice_total\n"
            "    assert invoice_total([(1, 250.0)], False) == 250.0\n"
            "\n"
            "\n"
            "def test_free_shipping_at_exact_threshold():\n"
            "    from solution import invoice_total\n"
            "    assert invoice_total([(1, 180.5)], False) == 180.5\n"
            "\n"
            "\n"
            "def test_vip_multiplier_applied_last():\n"
            "    from solution import invoice_total\n"
            "    assert invoice_total([(1, 100.0)], True) == 99.35\n"
            "\n"
            "\n"
            "def test_empty_items_only_shipping():\n"
            "    from solution import invoice_total\n"
            "    assert invoice_total([], False) == 12.9\n"
        ),
    },
    {
        "task_id": "log_formatter",
        "prompt": (
            "You are asked to implement a log line formatter in the file solution.py.\n"
            "It defines a single function `format_logs(lines: list[str]) -> list[str]`\n"
            "that converts raw pipe-separated log records into display strings, one\n"
            "output string per input line, preserving order. The exact output format\n"
            "and the error codes below are mandatory and checked verbatim by tests.\n\n"
            "Each input line should have exactly 3 fields separated by '|':\n"
            "LEVEL|code|message. Rules, applied per line:\n"
            "- If splitting on '|' does not yield exactly 3 fields, the output for that\n"
            "  line is the literal string 'ERR_07'.\n"
            "- Valid levels are exactly DEBUG, INFO, WARN and CRIT. If the level field\n"
            "  is not one of these, the output is the literal string 'ERR_04'.\n"
            "- Otherwise the output is '[LEVEL] #code :: message' (brackets around the\n"
            "  level, a '#' glued to the code, and ' :: ' before the message).\n"
            "- Additionally, lines whose level is CRIT get the prefix '!! ' prepended\n"
            "  to the formatted string (e.g. '!! [CRIT] #9 :: disk full').\n"
        ),
        "starter_code": (
            "def format_logs(lines: list[str]) -> list[str]:\n"
            '    """Format raw pipe-separated log records into display strings."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "from solution import format_logs\n"
            "\n"
            "\n"
            "def test_basic_info_line():\n"
            "    assert format_logs(['INFO|12|server started']) == ['[INFO] #12 :: server started']\n"
            "\n"
            "\n"
            "def test_malformed_line_err07():\n"
            "    assert format_logs(['INFO|only-two-fields']) == ['ERR_07']\n"
            "\n"
            "\n"
            "def test_too_many_fields_err07():\n"
            "    assert format_logs(['INFO|1|a|b']) == ['ERR_07']\n"
            "\n"
            "\n"
            "def test_unknown_level_err04():\n"
            "    assert format_logs(['TRACE|3|noise']) == ['ERR_04']\n"
            "\n"
            "\n"
            "def test_crit_prefix():\n"
            "    assert format_logs(['CRIT|9|disk full']) == ['!! [CRIT] #9 :: disk full']\n"
            "\n"
            "\n"
            "def test_order_preserved_mixed():\n"
            "    out = format_logs(['WARN|5|hot', 'BAD|1|x', 'oops'])\n"
            "    assert out == ['[WARN] #5 :: hot', 'ERR_04', 'ERR_07']\n"
            "\n"
            "\n"
            "def test_empty_input():\n"
            "    assert format_logs([]) == []\n"
        ),
    },
    {
        "task_id": "inventory_restock",
        "prompt": (
            "You are asked to implement an inventory restock reporting module split\n"
            "across two files that you must create in the workspace: a small data\n"
            "helper file and the main entry point file solution.py that the tests\n"
            "call. The filtering threshold, the restock formula, the sort order and\n"
            "the output format below are all mandatory and checked exactly.\n\n"
            "Files and functions:\n"
            "1. models.py must define `make_item(name: str, category: str, qty: int) -> dict`\n"
            "   returning the dict {'name': name, 'category': category, 'qty': qty}.\n"
            "2. solution.py must define `restock_report(items: list[dict]) -> list[str]`\n"
            "   which:\n"
            "   - keeps only items whose qty is STRICTLY less than 17 (qty == 17 is\n"
            "     excluded);\n"
            "   - computes the restock amount for each kept item as qty * 3 + 5;\n"
            "   - sorts the kept items by (category DESCENDING, name ASCENDING);\n"
            "   - returns one string per item in the exact format\n"
            "     'category/name:restock' (slash between category and name, colon\n"
            "     before the restock amount, no spaces).\n"
        ),
        "starter_code": (
            "def restock_report(items: list[dict]) -> list[str]:\n"
            '    """Build the restock report lines for the given inventory items."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_make_item_builds_dict():\n"
            "    from models import make_item\n"
            "    assert make_item('bolt', 'hw', 4) == {'name': 'bolt', 'category': 'hw', 'qty': 4}\n"
            "\n"
            "\n"
            "def test_threshold_is_strict():\n"
            "    from solution import restock_report\n"
            "    items = [{'name': 'a', 'category': 'x', 'qty': 17},\n"
            "             {'name': 'b', 'category': 'x', 'qty': 16}]\n"
            "    assert restock_report(items) == ['x/b:53']\n"
            "\n"
            "\n"
            "def test_restock_formula():\n"
            "    from solution import restock_report\n"
            "    assert restock_report([{'name': 'n', 'category': 'c', 'qty': 4}]) == ['c/n:17']\n"
            "\n"
            "\n"
            "def test_category_descending():\n"
            "    from solution import restock_report\n"
            "    items = [{'name': 'a', 'category': 'aaa', 'qty': 1},\n"
            "             {'name': 'a', 'category': 'zzz', 'qty': 1}]\n"
            "    assert restock_report(items) == ['zzz/a:8', 'aaa/a:8']\n"
            "\n"
            "\n"
            "def test_name_ascending_within_category():\n"
            "    from solution import restock_report\n"
            "    items = [{'name': 'zeta', 'category': 'c', 'qty': 2},\n"
            "             {'name': 'alpha', 'category': 'c', 'qty': 2}]\n"
            "    assert restock_report(items) == ['c/alpha:11', 'c/zeta:11']\n"
            "\n"
            "\n"
            "def test_zero_qty_included():\n"
            "    from solution import restock_report\n"
            "    assert restock_report([{'name': 'x', 'category': 'y', 'qty': 0}]) == ['y/x:5']\n"
            "\n"
            "\n"
            "def test_empty_inventory():\n"
            "    from solution import restock_report\n"
            "    assert restock_report([]) == []\n"
        ),
    },
    {
        "task_id": "rate_limiter_bucket",
        "prompt": (
            "You are asked to implement a deterministic token-bucket rate limiter in\n"
            "the file solution.py. It defines a single function\n"
            "`simulate(gaps: list[int]) -> list[bool]` that replays a sequence of\n"
            "requests and reports which ones were allowed. All the numeric parameters\n"
            "of the bucket are fixed constants given below and checked by tests.\n\n"
            "The bucket has capacity 23 tokens and starts full. Each element of `gaps`\n"
            "is the number of whole ticks elapsed since the previous request (the\n"
            "first element counts from the start). Processing each request in order:\n"
            "- First refill: add 4 tokens per elapsed tick, capping the bucket at its\n"
            "  capacity of 23 tokens.\n"
            "- Then the request costs exactly 5 tokens: if the bucket holds at least\n"
            "  5 tokens the request is allowed (append True) and 5 tokens are\n"
            "  removed; otherwise it is denied (append False) and NO tokens are\n"
            "  removed.\n"
            "Return the list of booleans, one per request, in order.\n"
        ),
        "starter_code": (
            "def simulate(gaps: list[int]) -> list[bool]:\n"
            '    """Replay requests through the token bucket; True = allowed."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "from solution import simulate\n"
            "\n"
            "\n"
            "def test_burst_from_full_bucket():\n"
            "    assert simulate([0, 0, 0, 0, 0]) == [True, True, True, True, False]\n"
            "\n"
            "\n"
            "def test_single_request_allowed():\n"
            "    assert simulate([0]) == [True]\n"
            "\n"
            "\n"
            "def test_refill_after_denial():\n"
            "    # esgota o balde, nega, depois 1 tick (+4) ainda nega (3+4=7>=5 permite!)\n"
            "    assert simulate([0, 0, 0, 0, 0, 1]) == [True, True, True, True, False, True]\n"
            "\n"
            "\n"
            "def test_capacity_cap():\n"
            "    # gap enorme não passa da capacidade: só 4 requests seguidos passam\n"
            "    assert simulate([100, 0, 0, 0, 0]) == [True, True, True, True, False]\n"
            "\n"
            "\n"
            "def test_denied_request_costs_nothing():\n"
            "    # após 4 permitidos restam 3; duas negações seguidas não mudam o saldo\n"
            "    assert simulate([0, 0, 0, 0, 0, 0]) == [True, True, True, True, False, False]\n"
            "\n"
            "\n"
            "def test_partial_refill_not_enough():\n"
            "    # 23 -> 4 permitidos (resta 3); nega; gap 0 nega de novo\n"
            "    out = simulate([0, 0, 0, 0, 0, 0, 1])\n"
            "    assert out == [True, True, True, True, False, False, True]\n"
            "\n"
            "\n"
            "def test_empty_gaps():\n"
            "    assert simulate([]) == []\n"
        ),
    },
    {
        "task_id": "grade_curve",
        "prompt": (
            "You are asked to implement a grade assignment function in the file\n"
            "solution.py. It defines `assign_grades(scores: list[float]) -> list[str]`\n"
            "which maps each numeric score to a letter grade, one letter per score,\n"
            "preserving order. A curve bonus and the exact grade cutoffs are given\n"
            "below; they are arbitrary and must be followed to the letter.\n\n"
            "For each score, first apply the curve: add a bonus of 3.2 points, round\n"
            "the result to 2 decimal places with round(x, 2), then cap it at 100.0\n"
            "(use min). Then map the curved score s to a letter using these cutoffs,\n"
            "checked from the top:\n"
            "- s >= 91.5  -> 'A'\n"
            "- s >= 77.25 -> 'B'\n"
            "- s >= 62.0  -> 'C'\n"
            "- s >= 48.75 -> 'D'\n"
            "- otherwise  -> 'F'\n"
            "Return the list of letter grades as strings.\n"
        ),
        "starter_code": (
            "def assign_grades(scores: list[float]) -> list[str]:\n"
            '    """Map each score to a letter grade after applying the curve."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "from solution import assign_grades\n"
            "\n"
            "\n"
            "def test_a_boundary():\n"
            "    assert assign_grades([88.3]) == ['A']\n"
            "\n"
            "\n"
            "def test_b_boundary():\n"
            "    assert assign_grades([74.05]) == ['B']\n"
            "\n"
            "\n"
            "def test_c_boundary():\n"
            "    assert assign_grades([58.8]) == ['C']\n"
            "\n"
            "\n"
            "def test_d_boundary():\n"
            "    assert assign_grades([45.55]) == ['D']\n"
            "\n"
            "\n"
            "def test_f_low_score():\n"
            "    assert assign_grades([10.0]) == ['F']\n"
            "\n"
            "\n"
            "def test_cap_at_100_is_a():\n"
            "    assert assign_grades([99.9]) == ['A']\n"
            "\n"
            "\n"
            "def test_just_below_a_is_b():\n"
            "    assert assign_grades([88.29]) == ['B']\n"
            "\n"
            "\n"
            "def test_order_preserved():\n"
            "    assert assign_grades([88.3, 10.0, 58.8]) == ['A', 'F', 'C']\n"
        ),
    },
    {
        "task_id": "config_renderer",
        "prompt": (
            "You are asked to implement a configuration file renderer split across\n"
            "two files that you must create in the workspace: a key validator helper\n"
            "file and the main entry point file solution.py that the tests call. The\n"
            "exact line prefix, separator token and error code given below are all\n"
            "mandatory and are compared verbatim by the tests.\n\n"
            "Files and functions:\n"
            "1. validators.py must define `is_valid_key(key: str) -> bool`: a key is\n"
            "   valid iff it is non-empty, contains only lowercase ASCII letters and\n"
            "   underscores, and does NOT start with an underscore.\n"
            "2. solution.py must define `render_config(pairs: list[tuple[str, str]]) -> str`\n"
            "   which renders one line per (key, value) pair, in order:\n"
            "   - if the key is valid, the line is 'CFG> ' + key + ' := ' + value\n"
            "     (note the exact 'CFG> ' prefix and the ' := ' separator);\n"
            "   - if the key is invalid, the line is exactly the literal 'E_KEY_9'.\n"
            "   Join all lines with a single newline character and return the string\n"
            "   (no trailing newline). An empty input list renders as ''.\n"
        ),
        "starter_code": (
            "def render_config(pairs: list[tuple[str, str]]) -> str:\n"
            '    """Render key/value pairs as configuration lines."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_validator_accepts_simple_key():\n"
            "    from validators import is_valid_key\n"
            "    assert is_valid_key('db_host') is True\n"
            "\n"
            "\n"
            "def test_validator_rejects_leading_underscore():\n"
            "    from validators import is_valid_key\n"
            "    assert is_valid_key('_private') is False\n"
            "\n"
            "\n"
            "def test_validator_rejects_uppercase_and_empty():\n"
            "    from validators import is_valid_key\n"
            "    assert is_valid_key('Host') is False\n"
            "    assert is_valid_key('') is False\n"
            "\n"
            "\n"
            "def test_render_single_valid_pair():\n"
            "    from solution import render_config\n"
            "    assert render_config([('port', '8080')]) == 'CFG> port := 8080'\n"
            "\n"
            "\n"
            "def test_render_invalid_key_error_code():\n"
            "    from solution import render_config\n"
            "    assert render_config([('9bad', 'x')]) == 'E_KEY_9'\n"
            "\n"
            "\n"
            "def test_render_mixed_lines_joined():\n"
            "    from solution import render_config\n"
            "    out = render_config([('a', '1'), ('_b', '2'), ('c_d', '3')])\n"
            "    assert out == 'CFG> a := 1\\nE_KEY_9\\nCFG> c_d := 3'\n"
            "\n"
            "\n"
            "def test_render_empty_list():\n"
            "    from solution import render_config\n"
            "    assert render_config([]) == ''\n"
        ),
    },
    {
        "task_id": "shift_cipher",
        "prompt": (
            "You are asked to implement a custom substitution cipher in the file\n"
            "solution.py. It defines a single function `encode(s: str) -> str` that\n"
            "maps each character of the input to an output character and returns the\n"
            "encoded string. Three different rotation amounts are used depending on\n"
            "the character class; the exact amounts are given below.\n\n"
            "Rules, applied independently to each character:\n"
            "- Lowercase ASCII letters are rotated forward by 11 positions within\n"
            "  the lowercase alphabet (wrapping around, e.g. 'z' wraps to 'k').\n"
            "- Uppercase ASCII letters are rotated forward by 19 positions within\n"
            "  the uppercase alphabet (wrapping around).\n"
            "- Decimal digits are rotated forward by 6 positions within '0'-'9'\n"
            "  (wrapping around, e.g. '9' wraps to '5').\n"
            "- Every other character (spaces, punctuation, etc.) is left unchanged.\n"
            "The empty string encodes to the empty string.\n"
        ),
        "starter_code": (
            "def encode(s: str) -> str:\n"
            '    """Encode s with the custom per-class rotation cipher."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "from solution import encode\n"
            "\n"
            "\n"
            "def test_lowercase_shift():\n"
            "    assert encode('a') == 'l'\n"
            "\n"
            "\n"
            "def test_lowercase_wraps():\n"
            "    assert encode('z') == 'k'\n"
            "\n"
            "\n"
            "def test_uppercase_shift():\n"
            "    assert encode('A') == 'T'\n"
            "\n"
            "\n"
            "def test_uppercase_wraps():\n"
            "    assert encode('Z') == 'S'\n"
            "\n"
            "\n"
            "def test_digit_shift_and_wrap():\n"
            "    assert encode('09') == '65'\n"
            "\n"
            "\n"
            "def test_punctuation_unchanged():\n"
            "    assert encode('!, .?') == '!, .?'\n"
            "\n"
            "\n"
            "def test_mixed_string():\n"
            "    assert encode('aA0 z!') == 'lT6 k!'\n"
            "\n"
            "\n"
            "def test_empty():\n"
            "    assert encode('') == ''\n"
        ),
    },
    {
        "task_id": "loyalty_points",
        "prompt": (
            "You are asked to implement a customer loyalty points calculator in the\n"
            "file solution.py. It defines a single function\n"
            "`compute_points(amount: float, tier: str) -> int` returning how many\n"
            "points a purchase earns. The earning rate, the tier multipliers and the\n"
            "big-purchase bonus are fixed constants given below.\n\n"
            "Computation, in this exact order:\n"
            "1. Base points: amount * 4.5.\n"
            "2. Tier multiplier applied to the base points: 'gold' multiplies by\n"
            "   1.75, 'silver' multiplies by 1.2, any other tier string multiplies\n"
            "   by 1.0.\n"
            "3. Truncate to an integer with int() (floor for these non-negative\n"
            "   values).\n"
            "4. Big-purchase bonus: if amount is STRICTLY greater than 320, add a\n"
            "   flat bonus of 250 points after the truncation (at exactly 320 there\n"
            "   is no bonus).\n"
            "Return the final integer number of points.\n"
        ),
        "starter_code": (
            "def compute_points(amount: float, tier: str) -> int:\n"
            '    """Compute loyalty points for a purchase amount and customer tier."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "from solution import compute_points\n"
            "\n"
            "\n"
            "def test_base_rate_no_tier():\n"
            "    assert compute_points(100.0, 'bronze') == 450\n"
            "\n"
            "\n"
            "def test_gold_multiplier():\n"
            "    assert compute_points(100.0, 'gold') == 787\n"
            "\n"
            "\n"
            "def test_silver_multiplier():\n"
            "    assert compute_points(100.0, 'silver') == 540\n"
            "\n"
            "\n"
            "def test_big_purchase_bonus():\n"
            "    assert compute_points(400.0, 'bronze') == 2050\n"
            "\n"
            "\n"
            "def test_no_bonus_at_exact_threshold():\n"
            "    assert compute_points(320.0, 'bronze') == 1440\n"
            "\n"
            "\n"
            "def test_gold_with_bonus():\n"
            "    assert compute_points(400.0, 'gold') == 3400\n"
            "\n"
            "\n"
            "def test_zero_amount():\n"
            "    assert compute_points(0.0, 'gold') == 0\n"
        ),
    },
    {
        "task_id": "csv_normalizer",
        "prompt": (
            "You are asked to implement a row normalizer for a tiny CSV-like format\n"
            "in the file solution.py. It defines a single function\n"
            "`normalize(rows: list[str]) -> list[str]` that cleans up each raw row\n"
            "string and returns the normalized rows in the same order. The exact\n"
            "delimiter, placeholder token and minimum width are specified below.\n\n"
            "For each row, apply these steps in order:\n"
            "1. Split the row on the ';' delimiter (semicolon, not comma).\n"
            "2. Strip leading/trailing whitespace from every field.\n"
            "3. Replace every field that is empty after stripping with the literal\n"
            "   placeholder 'N/A'.\n"
            "4. If the row has fewer than 3 fields, append 'N/A' fields until it has\n"
            "   exactly 3 (rows with 3 or more fields are left at their length).\n"
            "5. Uppercase the FIRST field only (the others keep their case).\n"
            "6. Re-join the fields with ';' and that is the output row.\n"
        ),
        "starter_code": (
            "def normalize(rows: list[str]) -> list[str]:\n"
            '    """Normalize raw semicolon-separated rows."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "from solution import normalize\n"
            "\n"
            "\n"
            "def test_strip_and_upper_first():\n"
            "    assert normalize([' ana ; x ; y ']) == ['ANA;x;y']\n"
            "\n"
            "\n"
            "def test_empty_field_placeholder():\n"
            "    assert normalize(['a;;c']) == ['A;N/A;c']\n"
            "\n"
            "\n"
            "def test_pad_short_row_to_three():\n"
            "    assert normalize(['solo']) == ['SOLO;N/A;N/A']\n"
            "\n"
            "\n"
            "def test_two_fields_padded():\n"
            "    assert normalize(['a;b']) == ['A;b;N/A']\n"
            "\n"
            "\n"
            "def test_long_row_not_truncated():\n"
            "    assert normalize(['a;b;c;d']) == ['A;b;c;d']\n"
            "\n"
            "\n"
            "def test_whitespace_only_field_is_placeholder():\n"
            "    assert normalize(['a;   ;c']) == ['A;N/A;c']\n"
            "\n"
            "\n"
            "def test_multiple_rows_order():\n"
            "    assert normalize(['a;b;c', 'd']) == ['A;b;c', 'D;N/A;N/A']\n"
            "\n"
            "\n"
            "def test_empty_input():\n"
            "    assert normalize([]) == []\n"
        ),
    },
    {
        "task_id": "api_router",
        "prompt": (
            "You are asked to implement a tiny HTTP-style path router split across\n"
            "two files that you must create in the workspace: a fallback handler\n"
            "file and the main entry point file solution.py that the tests call.\n"
            "The exact version prefix, route table and response strings given below\n"
            "are mandatory and compared verbatim by the tests.\n\n"
            "Files and functions:\n"
            "1. handlers.py must define `not_found() -> str` returning the literal\n"
            "   string 'RT_404_X'.\n"
            "2. solution.py must define `route(path: str) -> str`:\n"
            "   - every valid path must start with the version prefix '/api/v3';\n"
            "     any path that does not start with it returns not_found();\n"
            "   - '/api/v3/users'  returns 'users_handler'\n"
            "   - '/api/v3/items'  returns 'items_handler'\n"
            "   - '/api/v3/health' returns 'OK_200'\n"
            "   - any other path under the prefix (including '/api/v3' itself and\n"
            "     paths with trailing slashes) also returns not_found().\n"
            "   Matching is exact string comparison, no normalization.\n"
        ),
        "starter_code": (
            "def route(path: str) -> str:\n"
            '    """Route an HTTP-style path to its handler response string."""\n'
            "    raise NotImplementedError\n"
        ),
        "test_code": (
            "def test_not_found_literal():\n"
            "    from handlers import not_found\n"
            "    assert not_found() == 'RT_404_X'\n"
            "\n"
            "\n"
            "def test_users_route():\n"
            "    from solution import route\n"
            "    assert route('/api/v3/users') == 'users_handler'\n"
            "\n"
            "\n"
            "def test_items_route():\n"
            "    from solution import route\n"
            "    assert route('/api/v3/items') == 'items_handler'\n"
            "\n"
            "\n"
            "def test_health_route():\n"
            "    from solution import route\n"
            "    assert route('/api/v3/health') == 'OK_200'\n"
            "\n"
            "\n"
            "def test_wrong_version_prefix():\n"
            "    from solution import route\n"
            "    assert route('/api/v1/users') == 'RT_404_X'\n"
            "\n"
            "\n"
            "def test_unknown_route_under_prefix():\n"
            "    from solution import route\n"
            "    assert route('/api/v3/admin') == 'RT_404_X'\n"
            "\n"
            "\n"
            "def test_prefix_alone_is_not_found():\n"
            "    from solution import route\n"
            "    assert route('/api/v3') == 'RT_404_X'\n"
            "\n"
            "\n"
            "def test_trailing_slash_is_not_found():\n"
            "    from solution import route\n"
            "    assert route('/api/v3/users/') == 'RT_404_X'\n"
        ),
    },
]


def get_task(task_id: str) -> dict:
    for task in TASKS:
        if task["task_id"] == task_id:
            return task
    raise KeyError(task_id)
